@startuml

title internal implementation

box "Node 1" #white
participant Alice
participant StreamReference1
participant SimpleStreamProxy
end box

box "Node 2"
participant SimpleStream
end box

box "Node 3" #white
participant StreamReference2
participant Bob
end box

Alice -> StreamReference1: subscribe
StreamReference1 -> SimpleStreamProxy : subscribe
SimpleStreamProxy -> SimpleStream : subscribe

Bob -> StreamReference2: publish
StreamReference2 -> SimpleStream : publish
SimpleStream -> SimpleStreamProxy : onNext
SimpleStreamProxy -> Alice : observer.onNext

Alice -> StreamReference1: unsubscribe
StreamReference1 -> SimpleStreamProxy : unsubscribe
SimpleStreamProxy -> SimpleStream : unsubscribe

@enduml