apiVersion: v1
kind: Service
metadata:
    name: {{ include "orbit.fullname" . }}
spec:
    selector:
        app: {{ include "orbit.name" . }}
        release: {{ .Release.Name }}
        component: node
    ports:
        - name: grpc
          port: {{ .Values.node.containerPort }}
