apiVersion: v1
entries:
  orbit:
  - apiVersion: v1
    appVersion: 2.0.0-alpha.83
    created: "2020-07-18T00:19:49.886821558Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 8ce798a389204e86842a9be54a397ec077e66de42c847ee72fdb7f3137c12011
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.83/orbit-2.0.0-alpha.83.tgz
    version: 2.0.0-alpha.83
  - apiVersion: v1
    appVersion: 2.0.0-alpha.82
    created: "2020-07-07T22:57:58.94179044Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 4ff9dae5c8e2f87a19f8707ad0d2a4c86258390607e7cca159ca6fdb1473a6c4
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.82/orbit-2.0.0-alpha.82.tgz
    version: 2.0.0-alpha.82
  - apiVersion: v1
    appVersion: 2.0.0-alpha.81
    created: "2020-07-02T22:17:21.511730548Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 024b201b2a0e5f1d25dd34a7970fefb655f9644f68e1eab6fd1f42acfa819d66
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.81/orbit-2.0.0-alpha.81.tgz
    version: 2.0.0-alpha.81
  - apiVersion: v1
    appVersion: 2.0.0-alpha.80
    created: "2020-07-01T23:43:42.653833924Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 4d281c7e2a06ac677d78c46ca79fd4832782c636453f79f0f55ac6a13c36a9b2
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.80/orbit-2.0.0-alpha.80.tgz
    version: 2.0.0-alpha.80
  - apiVersion: v1
    appVersion: 2.0.0-alpha.67
    created: "2020-06-02T15:57:39.238696735Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 6aedc3b2db1eda89047a2992923094a3577757563ef9a524c291f77ee459c3e3
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.67/orbit-2.0.0-alpha.67.tgz
    version: 2.0.0-alpha.67
  - apiVersion: v1
    appVersion: 2.0.0-alpha.66
    created: "2020-05-28T14:36:06.605348494Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: b032bb1372be7749e417f2cd4b5fd662897476cdfd2a0b1c06782060ed17f264
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.66/orbit-2.0.0-alpha.66.tgz
    version: 2.0.0-alpha.66
  - apiVersion: v1
    appVersion: 2.0.0-alpha.65
    created: "2020-04-29T22:52:27.363631157Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: bce85a03654024bbff853f7cfca78d47bf8f6d2fde63537bafa064136dbc81de
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.65/orbit-2.0.0-alpha.65.tgz
    version: 2.0.0-alpha.65
  - apiVersion: v1
    appVersion: 2.0.0-alpha.64
    created: "2020-04-29T21:25:35.007338271Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: bb8417d8af334cbb6b481b9ffe81c20555f825cde7410bf91537f0e026fedc0e
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.64/orbit-2.0.0-alpha.64.tgz
    version: 2.0.0-alpha.64
  - apiVersion: v1
    appVersion: 2.0.0-alpha.63
    created: "2020-04-29T21:04:54.169286108Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 14426494ef72803e1c704446dd3c9e15baf7a99a7c7d680571aff6f968133b21
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.63/orbit-2.0.0-alpha.63.tgz
    version: 2.0.0-alpha.63
  - apiVersion: v1
    appVersion: 2.0.0-alpha.62
    created: "2020-04-28T21:16:48.776562645Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 13f3601a1acf8729edd2caa0096a704ea559b92342c463286af7fd515511619c
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.62/orbit-2.0.0-alpha.62.tgz
    version: 2.0.0-alpha.62
  - apiVersion: v1
    appVersion: 2.0.0-alpha.61
    created: "2020-04-23T18:49:37.224284296Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 50550c10c54b367b13af5d6c61d30d2e2b474342b6de72ff4e11e9570d4a2c9b
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.61/orbit-2.0.0-alpha.61.tgz
    version: 2.0.0-alpha.61
  - apiVersion: v1
    appVersion: 2.0.0-alpha.60
    created: "2020-04-14T18:18:14.285031028Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: b186996fd154477de7b605335ad86eb7f90bd213be905d0b06943e6d27201ec2
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.60/orbit-2.0.0-alpha.60.tgz
    version: 2.0.0-alpha.60
  - apiVersion: v1
    appVersion: 2.0.0-alpha.59
    created: "2020-03-17T23:08:13.560182128Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 44109765ac521e85c42c2cc8c10e940ea7356d8691eec21768d50e2cbbe30ba2
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.59/orbit-2.0.0-alpha.59.tgz
    version: 2.0.0-alpha.59
  - apiVersion: v1
    appVersion: 2.0.0-alpha.58
    created: "2020-03-17T19:42:41.715707055Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: fc857be3d2ab77a451ef96cd5d9263e0cc77195a689e584a42116e9bfcb05f62
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.58/orbit-2.0.0-alpha.58.tgz
    version: 2.0.0-alpha.58
  - apiVersion: v1
    appVersion: 2.0.0-alpha.56
    created: "2020-03-17T18:30:14.385667792Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 08ca46ba1b70ce1d2ea4a0bd2858d46c2b02e43b61a926baacea9b50294f67e7
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.56/orbit-2.0.0-alpha.56.tgz
    version: 2.0.0-alpha.56
  - apiVersion: v1
    appVersion: 2.0.0-alpha.55
    created: "2020-03-17T18:03:49.49435203Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: a54a471d1b1c2c137267b3fa9d58505ebea1357787f865f6d78ba445982497d6
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.55/orbit-2.0.0-alpha.55.tgz
    version: 2.0.0-alpha.55
  - apiVersion: v1
    appVersion: 2.0.0-alpha.54
    created: "2020-03-17T17:50:13.69251113Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 3542d05e47b61c92362770969277272a5f7fcc944cb23a2a91bddc8542b61704
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.54/orbit-2.0.0-alpha.54.tgz
    version: 2.0.0-alpha.54
  - apiVersion: v1
    appVersion: 2.0.0-alpha.53
    created: "2020-03-17T17:23:55.431795497Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: d1a8ce324e003c241fe1e704d126ff2c08939906fbe00b8fb39ae48cdac0d511
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.53/orbit-2.0.0-alpha.53.tgz
    version: 2.0.0-alpha.53
  - apiVersion: v1
    appVersion: 2.0.0-alpha.52
    created: "2020-03-17T16:37:02.698681404Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: b47a0f23ba49e381a8553bbbe26522482a26c88c9330b4794fd3ac0890b6b872
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.52/orbit-2.0.0-alpha.52.tgz
    version: 2.0.0-alpha.52
  - apiVersion: v1
    appVersion: 2.0.0-alpha.51
    created: "2020-03-17T00:02:55.714806612Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 0b7745718b070880a11c4a2243d604afd063be1c616c3830e1c217b2f07ed99c
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.51/orbit-2.0.0-alpha.51.tgz
    version: 2.0.0-alpha.51
  - apiVersion: v1
    appVersion: 2.0.0-alpha.50
    created: "2020-03-16T23:40:30.493109744Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 22048bfc1cf8370f03bae33a4de2b07478e23ccb7c55f67d1b447ed7397928b1
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.50/orbit-2.0.0-alpha.50.tgz
    version: 2.0.0-alpha.50
  - apiVersion: v1
    appVersion: 2.0.0-alpha.49
    created: "2020-03-16T23:26:32.84902973Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 1cd1e6d1b336689aa385bb5884afdc3d5cff2b9414b81ec0ecb72ac4228db602
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.49/orbit-2.0.0-alpha.49.tgz
    version: 2.0.0-alpha.49
  - apiVersion: v1
    appVersion: 2.0.0-alpha.48
    created: "2020-03-16T22:32:08.951011169Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: dd7023d043680c9946e0dd3df3e01ffe52b3997f7f35348d4a78ae4f22f85995
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.48/orbit-2.0.0-alpha.48.tgz
    version: 2.0.0-alpha.48
  - apiVersion: v1
    appVersion: 2.0.0-alpha.47
    created: "2020-03-16T22:18:07.792598642Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 0b7bfbae0e8cf88921380cf0551128f4b209ea8991293689f899996b11f392f2
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.47/orbit-2.0.0-alpha.47.tgz
    version: 2.0.0-alpha.47
  - apiVersion: v1
    appVersion: 2.0.0-alpha.46
    created: "2020-03-16T21:57:39.7158024Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 32b849d064af5325f936208995940c78172e854f657b6121562aee16a0dafc05
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.46/orbit-2.0.0-alpha.46.tgz
    version: 2.0.0-alpha.46
  - apiVersion: v1
    appVersion: 2.0.0-alpha.45
    created: "2020-03-16T21:48:54.945239749Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 226a61f1d357b97c5085fe7645b41372ed8b3f079d2d49bcfd020ef4cf84bb5f
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.45/orbit-2.0.0-alpha.45.tgz
    version: 2.0.0-alpha.45
  - apiVersion: v1
    appVersion: 2.0.0-alpha.44
    created: "2020-03-16T21:39:56.449268119Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: acb838211294ddfddd174ee977dbf07bd9af2bd1aabb9517ad645d4ed91b3768
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.44/orbit-2.0.0-alpha.44.tgz
    version: 2.0.0-alpha.44
  - apiVersion: v1
    appVersion: 2.0.0-alpha.43
    created: "2020-03-16T21:28:48.405914016Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: f395f4cb9f13b1fd55e88be373ed13aa22d3e167d807e03beeaafef5310f07fb
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.43/orbit-2.0.0-alpha.43.tgz
    version: 2.0.0-alpha.43
  - apiVersion: v1
    appVersion: 2.0.0-alpha.42
    created: "2020-03-16T21:18:43.789243463Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 3a5fd951647d1583bc83e92ec962fd6be366ac99c9ef550a5a58e168b3ac4b45
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.42/orbit-2.0.0-alpha.42.tgz
    version: 2.0.0-alpha.42
  - apiVersion: v1
    appVersion: 2.0.0-alpha.39
    created: "2020-03-12T00:22:53.861783136Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 61417e593ea1807ae18a40038e51dd791256aa6ff2b51a2cbd9783c5250142e8
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.39/orbit-2.0.0-alpha.39.tgz
    version: 2.0.0-alpha.39
  - apiVersion: v1
    appVersion: 2.0.0-alpha.36
    created: "2020-02-13T00:26:39.760344906Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 39033d3dd3c71cf838577588ada5b2f599deec88415ed4e50b89a38a030f2925
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.36/orbit-2.0.0-alpha.36.tgz
    version: 2.0.0-alpha.36
  - apiVersion: v1
    appVersion: 2.0.0-alpha.35
    created: "2020-02-12T21:44:20.351361621Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 84d88f26ee96a704a94861f7d3d4b11e59ec8880eb12d4af8ecc47c618c7280b
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.35/orbit-2.0.0-alpha.35.tgz
    version: 2.0.0-alpha.35
  - apiVersion: v1
    appVersion: 2.0.0-alpha.34
    created: "2020-02-07T20:09:57.93745297Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 1750e70a059b32409dc2a48a89b624fa420d12accb0327650795412ee5ee9bda
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.34/orbit-2.0.0-alpha.34.tgz
    version: 2.0.0-alpha.34
  - apiVersion: v1
    appVersion: 2.0.0-alpha.33
    created: "2020-02-07T18:39:04.371079017Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 6cf6e5316fae53dc2a40e4040a74a855bcc48b946565fb8ca3d20100b35e22bf
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.33/orbit-2.0.0-alpha.33.tgz
    version: 2.0.0-alpha.33
  - apiVersion: v1
    appVersion: 2.0.0-alpha.32
    created: "2020-01-31T15:42:30.515968282Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 120d0aa2a7ece3a11d4b1f044c422d678cadd64dea031c4aba26789d67fe7fa7
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.32/orbit-2.0.0-alpha.32.tgz
    version: 2.0.0-alpha.32
  - apiVersion: v1
    appVersion: 2.0.0-alpha.30
    created: "2020-01-30T20:10:26.874032531Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 13c964c023ce9400170ccf3eeb03b67f5e7b1b57027fa61f8d838ae1c7377b72
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.30/orbit-2.0.0-alpha.30.tgz
    version: 2.0.0-alpha.30
  - apiVersion: v1
    appVersion: 2.0.0-alpha.29
    created: "2020-01-28T00:40:55.459719529Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 6294b7d312bc558f026b4df17b7dcbb6c2bea1f7003472975d3c2e6a4d4f827a
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.29/orbit-2.0.0-alpha.29.tgz
    version: 2.0.0-alpha.29
  - apiVersion: v1
    appVersion: 2.0.0-alpha.27
    created: "2020-01-23T00:15:20.79142234Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 5e9cbe64833dc0556a7fab696662cff6e699facee74c0e8d5aa28560da07e92c
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.27/orbit-2.0.0-alpha.27.tgz
    version: 2.0.0-alpha.27
  - apiVersion: v1
    appVersion: 2.0.0-alpha.26
    created: "2020-01-22T01:08:36.800591485Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 2ce5c3d59f7b8c99c576aa547a7a80409d793596198e0798e213241465ff9e2d
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.26/orbit-2.0.0-alpha.26.tgz
    version: 2.0.0-alpha.26
  - apiVersion: v1
    appVersion: 2.0.0-alpha.25
    created: "2020-01-17T18:25:14.249718939Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: f9ebaab36f817d257958483bb75819c94c7c23a2257c2d40453e39591ea3a06c
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.25/orbit-2.0.0-alpha.25.tgz
    version: 2.0.0-alpha.25
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24.4
    created: "2020-01-17T17:58:39.106237456Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 1f41ea501a475ae0223c1de2a035e291e9c39b5c055ecee3fe9b92c169b3cca4
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24.4/orbit-2.0.0-alpha.24.4.tgz
    version: 2.0.0-alpha.24.4
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24.3
    created: "2020-01-17T01:48:10.181137297Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: 49baab6646c356fa29ccbd4c3a6be57e4adc1108033652185a29f181937d6e93
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24.3/orbit-2.0.0-alpha.24.3.tgz
    version: 2.0.0-alpha.24.3
  - apiVersion: v1
    appVersion: 2.0.0-alpha.24
    created: "2020-01-16T20:22:55.449918354Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: e405e28c0c6ca54be50c396839c05aace89bd7e01022e0f591e4facdbdbf9146
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.24/orbit-2.0.0-alpha.24.tgz
    version: 2.0.0-alpha.24
  - apiVersion: v1
    appVersion: 2.0.0-alpha.23.1
    created: "2020-01-16T20:03:16.600002798Z"
    description: An Orbit Mesh Helm chart for Kubernetes
    digest: b23b1a0ecf562429c337f117fc5a2765d01c8ccef7faa6bf9ecfc1cc508858bc
    name: orbit
    urls:
    - https://github.com/orbit/orbit/releases/download/v2.0.0-alpha.23.1/orbit-2.0.0-alpha.23.1.tgz
    version: 2.0.0-alpha.23.1
generated: "2020-07-18T00:19:49.830129961Z"
