@startuml

activate Handler_1
Handler_1 -> Handler_1 : ctx1.fireWrite
Handler_1 --> Handler_2 : onWrite
deactivate Handler_1

activate Handler_2
Handler_2 -> Handler_2 : ctx2.fireWrite
Handler_2 --> Handler_3 : onWrite
deactivate Handler_2

activate Handler_3
Handler_3 -> Handler_3 : ctx3.fireWrite
Handler_3 --> Connection : onWrite
deactivate Handler_3


activate Connection
Connection -> Connection : ctx4.fireRead
Connection --> Handler_3 : onRead
deactivate Connection

activate Handler_3
Handler_3 -> Handler_3 : ctx3.fireRead
Handler_3 --> Handler_2 : onRead
deactivate Handler_3

activate Handler_2
Handler_2 -> Handler_2 : ctx2.fireRead
Handler_2 --> Handler_1 : onRead
deactivate Handler_2

@enduml