apiVersion: v1
kind: Service
metadata:
  name: {{ include "orbit.fullname" . }}-addressable-directory
  labels:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
    chart: {{ include "orbit.chart" . }}
    component: addressable-directory
spec:
  selector:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
    component: addressable-directory
    tier: "persistence"
  ports:
  - name: client
    port: {{ .Values.addressableDirectory.clientPort }}
  - name: peer
    port: {{ .Values.addressableDirectory.peerPort }}
