{{- if gt (int .Values.nodeDirectory.replicas) 0 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orbit.fullname" . }}-node-directory
  labels:
    {{- include "orbit.selectorLabels" . | nindent 4 }}
    chart: {{ include "orbit.chart" . }}
    component: node-directory
    tier: "persistence"
spec:
  replicas: {{ .Values.nodeDirectory.replicas }}
  selector:
    matchLabels:
      {{- include "orbit.selectorLabels" . | nindent 6 }}
      component: node-directory
  template:
    metadata:
      labels:
        {{- include "orbit.selectorLabels" . | nindent 8 }}
        component: node-directory
        tier: "persistence"
    spec:
    {{- with .Values.nodeDirectory }}
      containers:
      - name: node-directory
        image: {{ .image.repository }}
        ports:
        - containerPort: {{ .clientPort }}
        - containerPort: {{ .peerPort }}
        env:
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: "http://node-directory:{{ .clientPort }}"
    {{- end }}
{{- end }}
