/*
 Copyright (C) 2015 Electronic Arts Inc.  All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions
 are met:

 1.  Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
 2.  Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in the
     documentation and/or other materials provided with the distribution.
 3.  Neither the name of Electronic Arts, Inc. ("EA") nor the names of
     its contributors may be used to endorse or promote products derived
     from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY ELECTRONIC ARTS AND ITS CONTRIBUTORS "AS IS" AND ANY
 EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL ELECTRONIC ARTS OR ITS CONTRIBUTORS BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.proto

package com.ea.orbit.actors.rpc;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RpcMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ea.orbit.actors.rpc.RpcMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 messageType = 1;</code>
     *
     * <pre>
     * test1
     * </pre>
     */
    boolean hasMessageType();
    /**
     * <code>optional uint32 messageType = 1;</code>
     *
     * <pre>
     * test1
     * </pre>
     */
    int getMessageType();

    /**
     * <code>optional uint32 messageId = 2;</code>
     */
    boolean hasMessageId();
    /**
     * <code>optional uint32 messageId = 2;</code>
     */
    int getMessageId();

    /**
     * <code>optional uint32 interfaceId = 3;</code>
     */
    boolean hasInterfaceId();
    /**
     * <code>optional uint32 interfaceId = 3;</code>
     */
    int getInterfaceId();

    /**
     * <code>optional uint32 methodId = 4;</code>
     */
    boolean hasMethodId();
    /**
     * <code>optional uint32 methodId = 4;</code>
     */
    int getMethodId();

    /**
     * <code>optional string objectId = 5;</code>
     */
    boolean hasObjectId();
    /**
     * <code>optional string objectId = 5;</code>
     */
    java.lang.String getObjectId();
    /**
     * <code>optional string objectId = 5;</code>
     */
    com.google.protobuf.ByteString
        getObjectIdBytes();

    /**
     * <code>optional bytes payload = 6;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional bytes payload = 6;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code com.ea.orbit.actors.rpc.RpcMessage}
   */
  public static final class RpcMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ea.orbit.actors.rpc.RpcMessage)
      RpcMessageOrBuilder {
    // Use RpcMessage.newBuilder() to construct.
    private RpcMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcMessage defaultInstance;
    public static RpcMessage getDefaultInstance() {
      return defaultInstance;
    }

    public RpcMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ea.orbit.actors.rpc.Msg.internal_static_com_ea_orbit_actors_rpc_RpcMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ea.orbit.actors.rpc.Msg.internal_static_com_ea_orbit_actors_rpc_RpcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ea.orbit.actors.rpc.Msg.RpcMessage.class, com.ea.orbit.actors.rpc.Msg.RpcMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcMessage> PARSER =
        new com.google.protobuf.AbstractParser<RpcMessage>() {
      public RpcMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>optional uint32 messageType = 1;</code>
     *
     * <pre>
     * test1
     * </pre>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 messageType = 1;</code>
     *
     * <pre>
     * test1
     * </pre>
     */
    public int getMessageType() {
      return messageType_;
    }

    public static final int MESSAGEID_FIELD_NUMBER = 2;
    private int messageId_;
    /**
     * <code>optional uint32 messageId = 2;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 messageId = 2;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    public static final int INTERFACEID_FIELD_NUMBER = 3;
    private int interfaceId_;
    /**
     * <code>optional uint32 interfaceId = 3;</code>
     */
    public boolean hasInterfaceId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 interfaceId = 3;</code>
     */
    public int getInterfaceId() {
      return interfaceId_;
    }

    public static final int METHODID_FIELD_NUMBER = 4;
    private int methodId_;
    /**
     * <code>optional uint32 methodId = 4;</code>
     */
    public boolean hasMethodId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint32 methodId = 4;</code>
     */
    public int getMethodId() {
      return methodId_;
    }

    public static final int OBJECTID_FIELD_NUMBER = 5;
    private java.lang.Object objectId_;
    /**
     * <code>optional string objectId = 5;</code>
     */
    public boolean hasObjectId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string objectId = 5;</code>
     */
    public java.lang.String getObjectId() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          objectId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string objectId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getObjectIdBytes() {
      java.lang.Object ref = objectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        objectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 6;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes payload = 6;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private void initFields() {
      messageType_ = 0;
      messageId_ = 0;
      interfaceId_ = 0;
      methodId_ = 0;
      objectId_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ea.orbit.actors.rpc.Msg.RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ea.orbit.actors.rpc.Msg.RpcMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ea.orbit.actors.rpc.RpcMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ea.orbit.actors.rpc.RpcMessage)
        com.ea.orbit.actors.rpc.Msg.RpcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ea.orbit.actors.rpc.Msg.internal_static_com_ea_orbit_actors_rpc_RpcMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ea.orbit.actors.rpc.Msg.internal_static_com_ea_orbit_actors_rpc_RpcMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ea.orbit.actors.rpc.Msg.RpcMessage.class, com.ea.orbit.actors.rpc.Msg.RpcMessage.Builder.class);
      }

      // Construct using com.ea.orbit.actors.rpc.Msg.RpcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        interfaceId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        methodId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        objectId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ea.orbit.actors.rpc.Msg.internal_static_com_ea_orbit_actors_rpc_RpcMessage_descriptor;
      }

      public com.ea.orbit.actors.rpc.Msg.RpcMessage getDefaultInstanceForType() {
        return com.ea.orbit.actors.rpc.Msg.RpcMessage.getDefaultInstance();
      }

      public com.ea.orbit.actors.rpc.Msg.RpcMessage build() {
        com.ea.orbit.actors.rpc.Msg.RpcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ea.orbit.actors.rpc.Msg.RpcMessage buildPartial() {
        com.ea.orbit.actors.rpc.Msg.RpcMessage result = new com.ea.orbit.actors.rpc.Msg.RpcMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.interfaceId_ = interfaceId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.methodId_ = methodId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.objectId_ = objectId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      private int bitField0_;

      private int messageType_ ;
      /**
       * <code>optional uint32 messageType = 1;</code>
       *
       * <pre>
       * test1
       * </pre>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 messageType = 1;</code>
       *
       * <pre>
       * test1
       * </pre>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional uint32 messageType = 1;</code>
       *
       * <pre>
       * test1
       * </pre>
       */
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 messageType = 1;</code>
       *
       * <pre>
       * test1
       * </pre>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 0;
        onChanged();
        return this;
      }

      private int messageId_ ;
      /**
       * <code>optional uint32 messageId = 2;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 messageId = 2;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>optional uint32 messageId = 2;</code>
       */
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000002;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 messageId = 2;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageId_ = 0;
        onChanged();
        return this;
      }

      private int interfaceId_ ;
      /**
       * <code>optional uint32 interfaceId = 3;</code>
       */
      public boolean hasInterfaceId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 interfaceId = 3;</code>
       */
      public int getInterfaceId() {
        return interfaceId_;
      }
      /**
       * <code>optional uint32 interfaceId = 3;</code>
       */
      public Builder setInterfaceId(int value) {
        bitField0_ |= 0x00000004;
        interfaceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 interfaceId = 3;</code>
       */
      public Builder clearInterfaceId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        interfaceId_ = 0;
        onChanged();
        return this;
      }

      private int methodId_ ;
      /**
       * <code>optional uint32 methodId = 4;</code>
       */
      public boolean hasMethodId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 methodId = 4;</code>
       */
      public int getMethodId() {
        return methodId_;
      }
      /**
       * <code>optional uint32 methodId = 4;</code>
       */
      public Builder setMethodId(int value) {
        bitField0_ |= 0x00000008;
        methodId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 methodId = 4;</code>
       */
      public Builder clearMethodId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        methodId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object objectId_ = "";
      /**
       * <code>optional string objectId = 5;</code>
       */
      public boolean hasObjectId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string objectId = 5;</code>
       */
      public java.lang.String getObjectId() {
        java.lang.Object ref = objectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            objectId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string objectId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getObjectIdBytes() {
        java.lang.Object ref = objectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          objectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string objectId = 5;</code>
       */
      public Builder setObjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        objectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string objectId = 5;</code>
       */
      public Builder clearObjectId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        objectId_ = getDefaultInstance().getObjectId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string objectId = 5;</code>
       */
      public Builder setObjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        objectId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 6;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes payload = 6;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 6;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes payload = 6;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000020);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ea.orbit.actors.rpc.RpcMessage)
    }

    static {
      defaultInstance = new RpcMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ea.orbit.actors.rpc.RpcMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ea_orbit_actors_rpc_RpcMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ea_orbit_actors_rpc_RpcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tMsg.proto\022\027com.ea.orbit.actors.rpc\"~\n\n" +
      "RpcMessage\022\023\n\013messageType\030\001 \001(\r\022\021\n\tmessa" +
      "geId\030\002 \001(\r\022\023\n\013interfaceId\030\003 \001(\r\022\020\n\010metho" +
      "dId\030\004 \001(\r\022\020\n\010objectId\030\005 \001(\t\022\017\n\007payload\030\006" +
      " \001(\014B\002H\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ea_orbit_actors_rpc_RpcMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ea_orbit_actors_rpc_RpcMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ea_orbit_actors_rpc_RpcMessage_descriptor,
        new java.lang.String[] { "MessageType", "MessageId", "InterfaceId", "MethodId", "ObjectId", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
