@startuml
"failedTransactionDemo" -> "Bank:jimmy" : [3] increment(15)
activate "Bank:jimmy"
"Bank:jimmy" --> "failedTransactionDemo" : [3; 2,423us] (response to increment): 15
deactivate "Bank:jimmy"
"failedTransactionDemo" -> "Store:all" : [5] buyItem(Bank:jimmy, Inventory:jimmy, ice cream, 10)
activate "Store:all"
"Store:all" -> "Transaction:rWKWdDqp6BFUNVTf" : [7] initTransaction(null, null)
"Store:all" -> "Bank:jimmy" : [8] decrement(10)
activate "Bank:jimmy"
"Store:all" -> "Inventory:jimmy" : [10] giveItem(ice cream)
activate "Inventory:jimmy"
"Bank:jimmy" -> "Transaction:rWKWdDqp6BFUNVTf" : [12] registerActor(Bank:jimmy)
"Bank:jimmy" --> "Store:all" : [8; 2,007us] (response to decrement): 5
deactivate "Bank:jimmy"
"Inventory:jimmy" --> "Store:all" : [10; 6,951us] (exception at giveItem):\njava.lang.IllegalArgumentException: \nSomething went wrong: ice cream
deactivate "Inventory:jimmy"
"Store:all" -> "Transaction:rWKWdDqp6BFUNVTf" : [13] cancelTransaction(null)
"Transaction:rWKWdDqp6BFUNVTf" -> "Bank:jimmy" : [14] cancelTransaction(rWKWdDqp6BFUNVTf)
activate "Bank:jimmy"
"Store:all" --> "failedTransactionDemo" : [5; 11,151us] (exception at buyItem):\njava.lang.IllegalArgumentException: \nSomething went wrong: ice cream
deactivate "Store:all"
"failedTransactionDemo" -> "Bank:jimmy" : [15] getBalance
activate "Bank:jimmy"
"Bank:jimmy" --> "Transaction:rWKWdDqp6BFUNVTf" : [14; 2,056us] (response to cancelTransaction): null
deactivate "Bank:jimmy"
"Bank:jimmy" --> "failedTransactionDemo" : [15; 1,441us] (response to getBalance): 15
deactivate "Bank:jimmy"
"failedTransactionDemo" -> "Inventory:jimmy" : [16] getItems
activate "Inventory:jimmy"
"Inventory:jimmy" --> "failedTransactionDemo" : [16; 475us] (response to getItems): []
deactivate "Inventory:jimmy"
@enduml
