@startuml
activate "simpleTransaction"
"simpleTransaction" -> "Transaction" : [3] initTransaction
activate "Transaction"
"simpleTransaction" -> "Jimmy:1" : [5] changePresets(5)
activate "Jimmy:1"
"Jimmy:1" -> "Transaction" : [7] registerActor(Jimmy:1)
"Jimmy:1" --> "simpleTransaction" : [5] (response to changePresets)
deactivate "Jimmy:1"
"simpleTransaction" -> "Transaction" : [8] transactionSuccessful
deactivate "Transaction"
deactivate "simpleTransaction"
@enduml
