# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: bitnami/etcd
  pullPolicy: IfNotPresent
  version: 2.0.0a18

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

clientPort: 2379
peerPort: 2380

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

node:
  replicas: 1
  containerPort: 50056

addressableDirectory:
  replicas: 1

nodeDirectory:
  replicas: 1

