@startuml
"successfulTransaction" -> "Bank:jimmy" : [3] increment(15)
activate "Bank:jimmy"
"Bank:jimmy" --> "successfulTransaction" : [3; 14,264us] (response to increment): 15
deactivate "Bank:jimmy"
"successfulTransaction" -> "Store:all" : [5] buyItem(Bank:jimmy, Inventory:jimmy, candy, 10)
activate "Store:all"
"Store:all" -> "Transaction:3o0eMm1Dv1xlBON1" : [7] initTransaction(null, null)
"Store:all" -> "Bank:jimmy" : [9] decrement(10)
activate "Bank:jimmy"
"Store:all" -> "Inventory:jimmy" : [10] giveItem(candy)
activate "Inventory:jimmy"
"Bank:jimmy" -> "Transaction:3o0eMm1Dv1xlBON1" : [12] registerActor(Bank:jimmy)
"Bank:jimmy" --> "Store:all" : [9; 1,205us] (response to decrement): 5
deactivate "Bank:jimmy"
"Inventory:jimmy" -> "Transaction:3o0eMm1Dv1xlBON1" : [14] registerActor(Inventory:jimmy)
"Inventory:jimmy" --> "Store:all" : [10; 35,186us] (response to giveItem): candy:aU8AeYQAyBV1r5KASwUpWD
deactivate "Inventory:jimmy"
"Store:all" -> "Transaction:3o0eMm1Dv1xlBON1" : [15] transactionSuccessful
"Store:all" --> "successfulTransaction" : [5; 50,179us] (response to buyItem): candy:aU8AeYQAyBV1r5KASwUpWD
deactivate "Store:all"
"successfulTransaction" -> "Bank:jimmy" : [16] getBalance
activate "Bank:jimmy"
"Bank:jimmy" --> "successfulTransaction" : [16; 1,405us] (response to getBalance): 5
deactivate "Bank:jimmy"
"successfulTransaction" -> "Inventory:jimmy" : [17] getItems
activate "Inventory:jimmy"
"Inventory:jimmy" --> "successfulTransaction" : [17; 1,451us] (response to getItems): [candy:aU8AeYQAyBV1r5KASwUpWD]
deactivate "Inventory:jimmy"
@enduml
